Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.define "j_master" do |j_master|
    j_master.vm.network "private_network", ip: "192.168.56.11"
    j_master.vm.provision "shell", path: "j-master.sh"
    j_master.vm.provider "virtualbox" do |vb|
        vb.name = "j_master"
        vb.cpus = 2
        vb.memory = 4096
    end
  end

  config.vm.define "j_worker" do |j_worker|
    j_worker.vm.network "private_network", ip: "192.168.56.12"
    j_worker.vm.provision "shell", path: "j-worker.sh"
    j_worker.vm.provider "virtualbox" do |vb|
        vb.name = "j_worker"
        vb.cpus = 2
        vb.memory = 4096
    end
  end
end