services:
  app:
    image: olka2/gunicorn:v1
    build: .
    networks:
      - app-network
    ports:
      - 8000:8000
    volumes:
      - app_data:/app


  nginx:
    image: nginx:latest
    networks:
      - app-network
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

networks:
  app-network:

volumes:
  app_data:
