Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "vm-nginx"
    vb.memory = 1024
    vb.cpus = 2
  end

  config.vm.network "public_network"
  config.vm.provision "shell", inline: <<-SHELL
      sudo apt update
      sudo apt install -y nginx
      systemctl enable nginx
      sudo sed -i 's/listen 80 default_server;/listen 8080 default_server;/g' /etc/nginx/sites-available/default
      sudo sed -i 's/listen \[::\]:80 default_server;/listen [::]:8080 default_server;/g' /etc/nginx/sites-available/default
      sudo systemctl restart nginx
  SHELL

end
